# InTAS: posiciones 10 celdas desde cells_centroids.csv
# origin=CELL_A01_1 ox=212750.0 oy=453200.0 scale=1.0

*.gNb[0].cellId = 1   # CELL_A01_1
*.gNb[0].mobility.initialX = 0.0m
*.gNb[0].mobility.initialY = 0.0m
*.gNb[0].mobility.initialZ = 10m

*.gNb[1].cellId = 2   # CELL_A01_10
*.gNb[1].mobility.initialX = 1600.0m
*.gNb[1].mobility.initialY = -1900.0m
*.gNb[1].mobility.initialZ = 10m

*.gNb[2].cellId = 3   # CELL_A01_2
*.gNb[2].mobility.initialX = 2700.0m
*.gNb[2].mobility.initialY = 600.0m
*.gNb[2].mobility.initialZ = 10m

*.gNb[3].cellId = 4   # CELL_A01_3
*.gNb[3].mobility.initialX = 600.0m
*.gNb[3].mobility.initialY = -700.0m
*.gNb[3].mobility.initialZ = 10m

*.gNb[4].cellId = 5   # CELL_A01_4
*.gNb[4].mobility.initialX = 300.0m
*.gNb[4].mobility.initialY = -1700.0m
*.gNb[4].mobility.initialZ = 10m

*.gNb[5].cellId = 6   # CELL_A01_5
*.gNb[5].mobility.initialX = 2200.0m
*.gNb[5].mobility.initialY = -1000.0m
*.gNb[5].mobility.initialZ = 10m

*.gNb[6].cellId = 7   # CELL_A01_6
*.gNb[6].mobility.initialX = 800.0m
*.gNb[6].mobility.initialY = -1900.0m
*.gNb[6].mobility.initialZ = 10m

*.gNb[7].cellId = 8   # CELL_A01_7
*.gNb[7].mobility.initialX = 1200.0m
*.gNb[7].mobility.initialY = -1700.0m
*.gNb[7].mobility.initialZ = 10m

*.gNb[8].cellId = 9   # CELL_A01_8
*.gNb[8].mobility.initialX = 2000.0m
*.gNb[8].mobility.initialY = -1500.0m
*.gNb[8].mobility.initialZ = 10m

*.gNb[9].cellId = 10   # CELL_A01_9
*.gNb[9].mobility.initialX = 1200.0m
*.gNb[9].mobility.initialY = -2100.0m
*.gNb[9].mobility.initialZ = 10m

