# InTAS: posiciones 4 celdas (escenario reducido de demostración)
# Subconjunto de cells_centroids.csv — celdas A01_1, A01_3, A01_4, A01_5
# origin=CELL_A01_1  ox=212750.0  oy=453200.0  scale=1.0

*.gNb[0].cellId = 1   # CELL_A01_1
*.gNb[0].mobility.initialX = 0.0m
*.gNb[0].mobility.initialY = 0.0m
*.gNb[0].mobility.initialZ = 10m

*.gNb[1].cellId = 4   # CELL_A01_3
*.gNb[1].mobility.initialX = 600.0m
*.gNb[1].mobility.initialY = -700.0m
*.gNb[1].mobility.initialZ = 10m

*.gNb[2].cellId = 5   # CELL_A01_4
*.gNb[2].mobility.initialX = 300.0m
*.gNb[2].mobility.initialY = -1700.0m
*.gNb[2].mobility.initialZ = 10m

*.gNb[3].cellId = 6   # CELL_A01_5
*.gNb[3].mobility.initialX = 2200.0m
*.gNb[3].mobility.initialY = -1000.0m
*.gNb[3].mobility.initialZ = 10m
